name: Build and Run Unit Tests (Manual)

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./Swindler/Swindler.sln
    - name: Build
      run: dotnet build ./Swindler/Swindler.sln --no-restore
    - name: Test
      run: dotnet test ./Swindler/Swindler.Tests.Unit/Swindler.Tests.Unit.csproj --no-build --verbosity normal
